export { default as Layout } from './Layout'
export { default as PostCard } from './PostCard'
export { default as NewsCard } from './NewsCard'
export { default as Pagination } from './Pagination'
export { default as Navigation } from './Navigation'
export { default as Slider } from './Slider'
export { default as InfoButtons } from './InfoButtons'
